# Generated by Django 3.0.3 on 2020-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('starting_position', models.CharField(max_length=100)),
                ('moves', models.TextField(default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('first_position', models.CharField(max_length=100)),
            ],
        ),
    ]
