# Generated by Django 3.0.3 on 2020-03-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openy', '0002_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='first_position',
            new_name='cover_position',
        ),
        migrations.AddField(
            model_name='exercise',
            name='first_move',
            field=models.BooleanField(default=True),
        ),
    ]
