# Generated by Django 3.0.3 on 2020-03-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openy', '0003_auto_20200325_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTraining',
            fields=[
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openy.Exercise')),
                ('depth', models.PositiveIntegerField()),
                ('partial', models.BooleanField()),
                ('successes', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('last_try', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openy.Node')),
            ],
        ),
    ]
