# Generated by Django 3.0.3 on 2020-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openy', '0004_positiontraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.FloatField(default=1000.0)),
                ('failure_coef', models.FloatField(default=1.0)),
                ('inactivity_coef', models.FloatField(default=1.0)),
                ('ease_coef', models.FloatField(default=1.0)),
                ('elo_spreading', models.FloatField(default=400)),
                ('elo_volatility', models.FloatField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='positiontraining',
            name='elo',
            field=models.FloatField(default=1000.0),
        ),
    ]
